version: '3.8'

services:
  redis-cluster-1:
    image: redis:7-alpine
    container_name: redis-cluster-1
    ports:
      - "7001:7001"
    command: >
      redis-server
      --port 7001
      --cluster-enabled yes
      --cluster-config-file nodes-7001.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --appendfilename appendonly-7001.aof
      --dbfilename dump-7001.rdb
      --logfile redis-7001.log
      --daemonize no
    volumes:
      - redis-cluster-1-data:/data
    networks:
      - redis-cluster-net

  redis-cluster-2:
    image: redis:7-alpine
    container_name: redis-cluster-2
    ports:
      - "7002:7002"
    command: >
      redis-server
      --port 7002
      --cluster-enabled yes
      --cluster-config-file nodes-7002.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --appendfilename appendonly-7002.aof
      --dbfilename dump-7002.rdb
      --logfile redis-7002.log
      --daemonize no
    volumes:
      - redis-cluster-2-data:/data
    networks:
      - redis-cluster-net

  redis-cluster-3:
    image: redis:7-alpine
    container_name: redis-cluster-3
    ports:
      - "7003:7003"
    command: >
      redis-server
      --port 7003
      --cluster-enabled yes
      --cluster-config-file nodes-7003.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --appendfilename appendonly-7003.aof
      --dbfilename dump-7003.rdb
      --logfile redis-7003.log
      --daemonize no
    volumes:
      - redis-cluster-3-data:/data
    networks:
      - redis-cluster-net

  redis-cluster-4:
    image: redis:7-alpine
    container_name: redis-cluster-4
    ports:
      - "7004:7004"
    command: >
      redis-server
      --port 7004
      --cluster-enabled yes
      --cluster-config-file nodes-7004.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --appendfilename appendonly-7004.aof
      --dbfilename dump-7004.rdb
      --logfile redis-7004.log
      --daemonize no
    volumes:
      - redis-cluster-4-data:/data
    networks:
      - redis-cluster-net

  redis-cluster-5:
    image: redis:7-alpine
    container_name: redis-cluster-5
    ports:
      - "7005:7005"
    command: >
      redis-server
      --port 7005
      --cluster-enabled yes
      --cluster-config-file nodes-7005.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --appendfilename appendonly-7005.aof
      --dbfilename dump-7005.rdb
      --logfile redis-7005.log
      --daemonize no
    volumes:
      - redis-cluster-5-data:/data
    networks:
      - redis-cluster-net

  redis-cluster-6:
    image: redis:7-alpine
    container_name: redis-cluster-6
    ports:
      - "7006:7006"
    command: >
      redis-server
      --port 7006
      --cluster-enabled yes
      --cluster-config-file nodes-7006.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --appendfilename appendonly-7006.aof
      --dbfilename dump-7006.rdb
      --logfile redis-7006.log
      --daemonize no
    volumes:
      - redis-cluster-6-data:/data
    networks:
      - redis-cluster-net

  redis-cluster-init:
    image: redis:7-alpine
    container_name: redis-cluster-init
    depends_on:
      - redis-cluster-1
      - redis-cluster-2
      - redis-cluster-3
      - redis-cluster-4
      - redis-cluster-5
      - redis-cluster-6
    command: >
      sh -c "
        sleep 10 &&
        redis-cli --cluster create
        redis-cluster-1:7001
        redis-cluster-2:7002
        redis-cluster-3:7003
        redis-cluster-4:7004
        redis-cluster-5:7005
        redis-cluster-6:7006
        --cluster-replicas 1 --cluster-yes
      "
    networks:
      - redis-cluster-net

networks:
  redis-cluster-net:
    driver: bridge

volumes:
  redis-cluster-1-data:
  redis-cluster-2-data:
  redis-cluster-3-data:
  redis-cluster-4-data:
  redis-cluster-5-data:
  redis-cluster-6-data: