version: '3.8'

services:
  redis-cluster:
    image: docker.io/bitnami/redis-cluster:7.4
    container_name: redis-cluster
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_CLUSTER_REPLICAS=0'
      - 'REDIS_NODES=redis-cluster redis-cluster redis-cluster'
      - 'REDIS_CLUSTER_CREATOR=yes'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_CLUSTER_ANNOUNCE_IP=redis-cluster'
    ports:
      - '6380:6380'
    networks:
      - redis-cluster
    volumes:
      - redis-cluster-data:/data

networks:
  redis-cluster:
    driver: bridge

volumes:
  redis-cluster-data:
